package com.onewifi.service;
// Generated Nov 13, 2015 5:55:46 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * Customerbalance generated by hbm2java
 */
public class AccountSummaryBean implements java.io.Serializable {


     private Date latestLoginTime;
	 private Date latestLogoutTime;
	 private String latestPosition;
 	 private double latestTopupAmount;
	 private double consumedAmount;
	 private double totalFlowInKB;

    public AccountSummaryBean() {
    }

    public Date getLatestLoginTime() {
        return this.latestLoginTime;
    }
    
    public void setLatestLoginTime(Date latestLoginTime) {
        this.latestLoginTime = latestLoginTime;
    }
	
	public Date getLatestLogoutTime() {
        return this.latestLogoutTime;
    }
    
    public void setLatestLogoutTime(Date latestLogoutTime) {
        this.latestLogoutTime = latestLogoutTime;
    }
		
	public String getLatestPosition() {
        return this.latestPosition;
    }
    
    public void setLatestPosition(String latestPosition) {
        this.latestPosition = latestPosition;
    }
	
    public double getLatestTopupAmount() {
        return this.latestTopupAmount;
    }
    
    public void setLatestTopupAmount(double latestTopupAmount) {
        this.latestTopupAmount = latestTopupAmount;
    }

	public double getConsumedAmount() {
        return this.consumedAmount;
    }
    
    public void setConsumedAmount(double consumedAmount) {
        this.consumedAmount = consumedAmount;
    }
	
	public double getTotalFlowInKB() {
        return this.totalFlowInKB;
    }
    
    public void setTotalFlowInKB(double totalFlowInKB) {
        this.totalFlowInKB = totalFlowInKB;
    }


}


