package com.onewifi.beans;
// Generated Nov 23, 2015 4:30:43 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * Customerbalance generated by hbm2java
 */
public class Customerbalance  implements java.io.Serializable {


     private CustomerbalanceId id;
     private Customermaster customermaster;
     private Devicemaster devicemaster;
     private Date balanceUpdatedDate;
     private double balanceAmount;

    public Customerbalance() {
    }

    public Customerbalance(CustomerbalanceId id, Customermaster customermaster, Devicemaster devicemaster, Date balanceUpdatedDate, double balanceAmount) {
       this.id = id;
       this.customermaster = customermaster;
       this.devicemaster = devicemaster;
       this.balanceUpdatedDate = balanceUpdatedDate;
       this.balanceAmount = balanceAmount;
    }
   
    public CustomerbalanceId getId() {
        return this.id;
    }
    
    public void setId(CustomerbalanceId id) {
        this.id = id;
    }
    public Customermaster getCustomermaster() {
        return this.customermaster;
    }
    
    public void setCustomermaster(Customermaster customermaster) {
        this.customermaster = customermaster;
    }
    public Devicemaster getDevicemaster() {
        return this.devicemaster;
    }
    
    public void setDevicemaster(Devicemaster devicemaster) {
        this.devicemaster = devicemaster;
    }
    public Date getBalanceUpdatedDate() {
        return this.balanceUpdatedDate;
    }
    
    public void setBalanceUpdatedDate(Date balanceUpdatedDate) {
        this.balanceUpdatedDate = balanceUpdatedDate;
    }
    public double getBalanceAmount() {
        return this.balanceAmount;
    }
    
    public void setBalanceAmount(double balanceAmount) {
        this.balanceAmount = balanceAmount;
    }




}


