package com.onewifi.beans;
// Generated Nov 23, 2015 4:30:43 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * Customerdevice generated by hbm2java
 */
public class Customerdevice  implements java.io.Serializable {


     private CustomerdeviceId id;
     private Customermaster customermaster;
     private Devicemaster devicemaster;
     private Statuscodemaster statuscodemaster;
     private Date endTimeQueried;

    public Customerdevice() {
    }

	
    public Customerdevice(CustomerdeviceId id, Customermaster customermaster, Devicemaster devicemaster, Statuscodemaster statuscodemaster) {
        this.id = id;
        this.customermaster = customermaster;
        this.devicemaster = devicemaster;
        this.statuscodemaster = statuscodemaster;
    }
    public Customerdevice(CustomerdeviceId id, Customermaster customermaster, Devicemaster devicemaster, Statuscodemaster statuscodemaster, Date endTimeQueried) {
       this.id = id;
       this.customermaster = customermaster;
       this.devicemaster = devicemaster;
       this.statuscodemaster = statuscodemaster;
       this.endTimeQueried = endTimeQueried;
    }
   
    public CustomerdeviceId getId() {
        return this.id;
    }
    
    public void setId(CustomerdeviceId id) {
        this.id = id;
    }
    public Customermaster getCustomermaster() {
        return this.customermaster;
    }
    
    public void setCustomermaster(Customermaster customermaster) {
        this.customermaster = customermaster;
    }
    public Devicemaster getDevicemaster() {
        return this.devicemaster;
    }
    
    public void setDevicemaster(Devicemaster devicemaster) {
        this.devicemaster = devicemaster;
    }
    public Statuscodemaster getStatuscodemaster() {
        return this.statuscodemaster;
    }
    
    public void setStatuscodemaster(Statuscodemaster statuscodemaster) {
        this.statuscodemaster = statuscodemaster;
    }
    public Date getEndTimeQueried() {
        return this.endTimeQueried;
    }
    
    public void setEndTimeQueried(Date endTimeQueried) {
        this.endTimeQueried = endTimeQueried;
    }




}


