package com.onewifi.beans;
// Generated Nov 23, 2015 3:35:31 PM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;
import java.util.ArrayList;
import java.util.List;

/**
 * Devicemaster generated by hbm2java
 */
public class Devicemaster  implements java.io.Serializable {


     private String deviceId;
     private Statuscodemaster statuscodemaster;
     private String userCode;
     private String password;
     private String partnerCode;
     private String imei;
     private String deviceSerialNo;
     private String deviceBoundStatus;
	 private int packageCount;
	 private int payAsYouGoCount;
     private Set<Customerbalance> customerbalances = new HashSet<Customerbalance>(0);
     private Set<Customerdevice> customerdevices = new HashSet<Customerdevice>(0);
     private Set<Customertopup> customertopups = new HashSet<Customertopup>(0);
	 private List<Customertopup> unFilledCustomertopups = new ArrayList<Customertopup>(0);
	 
    public Devicemaster() {
    }

	
    public Devicemaster(String deviceId, Statuscodemaster statuscodemaster, String userCode, String password, String partnerCode, String imei, String deviceSerialNo) {
        this.deviceId = deviceId;
        this.statuscodemaster = statuscodemaster;
        this.userCode = userCode;
        this.password = password;
        this.partnerCode = partnerCode;
        this.imei = imei;
        this.deviceSerialNo = deviceSerialNo;
    }
    public Devicemaster(String deviceId, Statuscodemaster statuscodemaster, String userCode, String password, String partnerCode, String imei, String deviceSerialNo, String deviceBoundStatus, Set<Customerbalance> customerbalances, Set<Customerdevice> customerdevices, Set<Customertopup> customertopups) {
       this.deviceId = deviceId;
       this.statuscodemaster = statuscodemaster;
       this.userCode = userCode;
       this.password = password;
       this.partnerCode = partnerCode;
       this.imei = imei;
       this.deviceSerialNo = deviceSerialNo;
       this.deviceBoundStatus = deviceBoundStatus;
       this.customerbalances = customerbalances;
       this.customerdevices = customerdevices;
       this.customertopups = customertopups;
    }
   
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
    public Statuscodemaster getStatuscodemaster() {
        return this.statuscodemaster;
    }
    
    public void setStatuscodemaster(Statuscodemaster statuscodemaster) {
        this.statuscodemaster = statuscodemaster;
    }
    public String getUserCode() {
        return this.userCode;
    }
    
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPartnerCode() {
        return this.partnerCode;
    }
    
    public void setPartnerCode(String partnerCode) {
        this.partnerCode = partnerCode;
    }
    public String getImei() {
        return this.imei;
    }
    
    public void setImei(String imei) {
        this.imei = imei;
    }
    public String getDeviceSerialNo() {
        return this.deviceSerialNo;
    }
    
    public void setDeviceSerialNo(String deviceSerialNo) {
        this.deviceSerialNo = deviceSerialNo;
    }
    public String getDeviceBoundStatus() {
        return this.deviceBoundStatus;
    }
    
    public void setDeviceBoundStatus(String deviceBoundStatus) {
        this.deviceBoundStatus = deviceBoundStatus;
    }
    public Set<Customerbalance> getCustomerbalances() {
        return this.customerbalances;
    }
    
    public void setCustomerbalances(Set<Customerbalance> customerbalances) {
        this.customerbalances = customerbalances;
    }
    public Set<Customerdevice> getCustomerdevices() {
        return this.customerdevices;
    }
    
    public void setCustomerdevices(Set<Customerdevice> customerdevices) {
        this.customerdevices = customerdevices;
    }
    public Set<Customertopup> getCustomertopups() {
        return this.customertopups;
    }
    
    public void setCustomertopups(Set<Customertopup> customertopups) {
        this.customertopups = customertopups;
    }

	public List<Customertopup> getUnFilledCustomertopups() {
        return this.unFilledCustomertopups;
    }
    
    public void setUnFilledCustomertopups(List<Customertopup> unFilledCustomertopups) {
        this.unFilledCustomertopups = unFilledCustomertopups;
    }

    public void setPackageCount(int packageCount) {
        this.packageCount = packageCount;
    }
    public int getPackageCount() {
        return this.packageCount;
    }
	
    public void setPayAsYouGoCount(int payAsYouGoCount) {
        this.payAsYouGoCount = payAsYouGoCount;
    }
    public int getPayAsYouGoCount() {
        return this.payAsYouGoCount;
    }	

}


