package com.onewifi.beans;
// Generated Oct 18, 2015 11:24:08 PM by Hibernate Tools 4.3.1.Final



/**
 * KeyvaluemasterId generated by hbm2java
 */
public class KeyvaluemasterId  implements java.io.Serializable {


     private String id;
     private String type;
     private String keyInfo;
     private String value;
     private int sortOrder;

    public KeyvaluemasterId() {
    }

    public KeyvaluemasterId(String id, String type, String keyInfo, String value, int sortOrder) {
       this.id = id;
       this.type = type;
       this.keyInfo = keyInfo;
       this.value = value;
       this.sortOrder = sortOrder;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getKeyInfo() {
        return this.keyInfo;
    }
    
    public void setKeyInfo(String keyInfo) {
        this.keyInfo = keyInfo;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public int getSortOrder() {
        return this.sortOrder;
    }
    
    public void setSortOrder(int sortOrder) {
        this.sortOrder = sortOrder;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof KeyvaluemasterId) ) return false;
		 KeyvaluemasterId castOther = ( KeyvaluemasterId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && ( (this.getKeyInfo()==castOther.getKeyInfo()) || ( this.getKeyInfo()!=null && castOther.getKeyInfo()!=null && this.getKeyInfo().equals(castOther.getKeyInfo()) ) )
 && ( (this.getValue()==castOther.getValue()) || ( this.getValue()!=null && castOther.getValue()!=null && this.getValue().equals(castOther.getValue()) ) )
 && (this.getSortOrder()==castOther.getSortOrder());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + ( getKeyInfo() == null ? 0 : this.getKeyInfo().hashCode() );
         result = 37 * result + ( getValue() == null ? 0 : this.getValue().hashCode() );
         result = 37 * result + this.getSortOrder();
         return result;
   }   


}


