package com.onewifi.beans;
// Generated Nov 23, 2015 4:30:43 PM by Hibernate Tools 4.3.1.Final



/**
 * Packagemaster generated by hbm2java
 */
public class Packagemaster  implements java.io.Serializable {


     private String packageTypeCode;
     private String packageTypeName;

    public Packagemaster() {
    }

    public Packagemaster(String packageTypeCode, String packageTypeName) {
       this.packageTypeCode = packageTypeCode;
       this.packageTypeName = packageTypeName;
    }
   
    public String getPackageTypeCode() {
        return this.packageTypeCode;
    }
    
    public void setPackageTypeCode(String packageTypeCode) {
        this.packageTypeCode = packageTypeCode;
    }
    public String getPackageTypeName() {
        return this.packageTypeName;
    }
    
    public void setPackageTypeName(String packageTypeName) {
        this.packageTypeName = packageTypeName;
    }




}


