package com.onewifi.beans;
// Generated Nov 23, 2015 4:30:43 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * Partnermaster generated by hbm2java
 */
public class Partnermaster  implements java.io.Serializable {


     private String partnerId;
     private String loginId;
     private String password;
     private String firstName;
     private String lastName;
     private String address;
     private Date creationDate;

    public Partnermaster() {
    }

    public Partnermaster(String partnerId, String loginId, String password, String firstName, String lastName, String address, Date creationDate) {
       this.partnerId = partnerId;
       this.loginId = loginId;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.creationDate = creationDate;
    }
   
    public String getPartnerId() {
        return this.partnerId;
    }
    
    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId;
    }
    public String getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }




}


