package com.onewifi.beans;
// Generated Nov 23, 2015 4:30:43 PM by Hibernate Tools 4.3.1.Final



/**
 * Pricing generated by hbm2java
 */
public class Pricing  implements java.io.Serializable {


     private PricingId id;
     private String country;
     private Double payAsYouGo;
     private String daily150mb;
     private String days7450mb;
     private String days301gb;
     private String days902gb;
     private String days1803gb;
     private String day1Pass;
     private String days5Pass;
     private String days10Pass;
     private String days20Pass;

    public Pricing() {
    }

	
    public Pricing(PricingId id, String country) {
        this.id = id;
        this.country = country;
    }
    public Pricing(PricingId id, String country, Double payAsYouGo, String daily150mb, String days7450mb, String days301gb, String days902gb, String days1803gb, String day1Pass, String days5Pass, String days10Pass, String days20Pass) {
       this.id = id;
       this.country = country;
       this.payAsYouGo = payAsYouGo;
       this.daily150mb = daily150mb;
       this.days7450mb = days7450mb;
       this.days301gb = days301gb;
       this.days902gb = days902gb;
       this.days1803gb = days1803gb;
       this.day1Pass = day1Pass;
       this.days5Pass = days5Pass;
       this.days10Pass = days10Pass;
       this.days20Pass = days20Pass;
    }
   
    public PricingId getId() {
        return this.id;
    }
    
    public void setId(PricingId id) {
        this.id = id;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Double getPayAsYouGo() {
        return this.payAsYouGo;
    }
    
    public void setPayAsYouGo(Double payAsYouGo) {
        this.payAsYouGo = payAsYouGo;
    }
    public String getDaily150mb() {
        return this.daily150mb;
    }
    
    public void setDaily150mb(String daily150mb) {
        this.daily150mb = daily150mb;
    }
    public String getDays7450mb() {
        return this.days7450mb;
    }
    
    public void setDays7450mb(String days7450mb) {
        this.days7450mb = days7450mb;
    }
    public String getDays301gb() {
        return this.days301gb;
    }
    
    public void setDays301gb(String days301gb) {
        this.days301gb = days301gb;
    }
    public String getDays902gb() {
        return this.days902gb;
    }
    
    public void setDays902gb(String days902gb) {
        this.days902gb = days902gb;
    }
    public String getDays1803gb() {
        return this.days1803gb;
    }
    
    public void setDays1803gb(String days1803gb) {
        this.days1803gb = days1803gb;
    }
    public String getDay1Pass() {
        return this.day1Pass;
    }
    
    public void setDay1Pass(String day1Pass) {
        this.day1Pass = day1Pass;
    }
    public String getDays5Pass() {
        return this.days5Pass;
    }
    
    public void setDays5Pass(String days5Pass) {
        this.days5Pass = days5Pass;
    }
    public String getDays10Pass() {
        return this.days10Pass;
    }
    
    public void setDays10Pass(String days10Pass) {
        this.days10Pass = days10Pass;
    }
    public String getDays20Pass() {
        return this.days20Pass;
    }
    
    public void setDays20Pass(String days20Pass) {
        this.days20Pass = days20Pass;
    }




}


