package com.onewifi.beans;
// Generated Nov 23, 2015 4:30:43 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * PricingId generated by hbm2java
 */
public class PricingId  implements java.io.Serializable {


     private String pricingId;
     private Date validDate;
     private String productCode;

    public PricingId() {
    }

    public PricingId(String pricingId, Date validDate, String productCode) {
       this.pricingId = pricingId;
       this.validDate = validDate;
       this.productCode = productCode;
    }
   
    public String getPricingId() {
        return this.pricingId;
    }
    
    public void setPricingId(String pricingId) {
        this.pricingId = pricingId;
    }
    public Date getValidDate() {
        return this.validDate;
    }
    
    public void setValidDate(Date validDate) {
        this.validDate = validDate;
    }
    public String getProductCode() {
        return this.productCode;
    }
    
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PricingId) ) return false;
		 PricingId castOther = ( PricingId ) other; 
         
		 return ( (this.getPricingId()==castOther.getPricingId()) || ( this.getPricingId()!=null && castOther.getPricingId()!=null && this.getPricingId().equals(castOther.getPricingId()) ) )
 && ( (this.getValidDate()==castOther.getValidDate()) || ( this.getValidDate()!=null && castOther.getValidDate()!=null && this.getValidDate().equals(castOther.getValidDate()) ) )
 && ( (this.getProductCode()==castOther.getProductCode()) || ( this.getProductCode()!=null && castOther.getProductCode()!=null && this.getProductCode().equals(castOther.getProductCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPricingId() == null ? 0 : this.getPricingId().hashCode() );
         result = 37 * result + ( getValidDate() == null ? 0 : this.getValidDate().hashCode() );
         result = 37 * result + ( getProductCode() == null ? 0 : this.getProductCode().hashCode() );
         return result;
   }   


}


