package com.onewifi.beans;
// Generated Nov 23, 2015 4:30:43 PM by Hibernate Tools 4.3.1.Final



/**
 * Retailerdevice generated by hbm2java
 */
public class Retailerdevice  implements java.io.Serializable {


     private RetailerdeviceId id;
     private String purpose;
     private double days;
     private double price;

    public Retailerdevice() {
    }

    public Retailerdevice(RetailerdeviceId id, String purpose, double days, double price) {
       this.id = id;
       this.purpose = purpose;
       this.days = days;
       this.price = price;
    }
   
    public RetailerdeviceId getId() {
        return this.id;
    }
    
    public void setId(RetailerdeviceId id) {
        this.id = id;
    }
    public String getPurpose() {
        return this.purpose;
    }
    
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }
    public double getDays() {
        return this.days;
    }
    
    public void setDays(double days) {
        this.days = days;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }




}


