package com.onewifi.beans;
// Generated Nov 23, 2015 4:30:43 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * Retailermaster generated by hbm2java
 */
public class Retailermaster  implements java.io.Serializable {


     private String retailerId;
     private String loginId;
     private String userName;
     private String password;
     private String coyRetailerName;
     private Integer coyContactNumber;
     private String directorName;
     private String identityId;
     private String address;
     private Integer retailerContactNumber;
     private Date creationDate;
     private String secretQuestion1;
     private String secretQuestionAnswer1;
     private String secretQuestion2;
     private String secretQuestionAnswer2;

    public Retailermaster() {
    }

	
    public Retailermaster(String retailerId, String loginId, String userName, String password, String coyRetailerName, String directorName, String identityId, String address, Date creationDate, String secretQuestion1, String secretQuestionAnswer1, String secretQuestion2, String secretQuestionAnswer2) {
        this.retailerId = retailerId;
        this.loginId = loginId;
        this.userName = userName;
        this.password = password;
        this.coyRetailerName = coyRetailerName;
        this.directorName = directorName;
        this.identityId = identityId;
        this.address = address;
        this.creationDate = creationDate;
        this.secretQuestion1 = secretQuestion1;
        this.secretQuestionAnswer1 = secretQuestionAnswer1;
        this.secretQuestion2 = secretQuestion2;
        this.secretQuestionAnswer2 = secretQuestionAnswer2;
    }
    public Retailermaster(String retailerId, String loginId, String userName, String password, String coyRetailerName, Integer coyContactNumber, String directorName, String identityId, String address, Integer retailerContactNumber, Date creationDate, String secretQuestion1, String secretQuestionAnswer1, String secretQuestion2, String secretQuestionAnswer2) {
       this.retailerId = retailerId;
       this.loginId = loginId;
       this.userName = userName;
       this.password = password;
       this.coyRetailerName = coyRetailerName;
       this.coyContactNumber = coyContactNumber;
       this.directorName = directorName;
       this.identityId = identityId;
       this.address = address;
       this.retailerContactNumber = retailerContactNumber;
       this.creationDate = creationDate;
       this.secretQuestion1 = secretQuestion1;
       this.secretQuestionAnswer1 = secretQuestionAnswer1;
       this.secretQuestion2 = secretQuestion2;
       this.secretQuestionAnswer2 = secretQuestionAnswer2;
    }
   
    public String getRetailerId() {
        return this.retailerId;
    }
    
    public void setRetailerId(String retailerId) {
        this.retailerId = retailerId;
    }
    public String getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getCoyRetailerName() {
        return this.coyRetailerName;
    }
    
    public void setCoyRetailerName(String coyRetailerName) {
        this.coyRetailerName = coyRetailerName;
    }
    public Integer getCoyContactNumber() {
        return this.coyContactNumber;
    }
    
    public void setCoyContactNumber(Integer coyContactNumber) {
        this.coyContactNumber = coyContactNumber;
    }
    public String getDirectorName() {
        return this.directorName;
    }
    
    public void setDirectorName(String directorName) {
        this.directorName = directorName;
    }
    public String getIdentityId() {
        return this.identityId;
    }
    
    public void setIdentityId(String identityId) {
        this.identityId = identityId;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Integer getRetailerContactNumber() {
        return this.retailerContactNumber;
    }
    
    public void setRetailerContactNumber(Integer retailerContactNumber) {
        this.retailerContactNumber = retailerContactNumber;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getSecretQuestion1() {
        return this.secretQuestion1;
    }
    
    public void setSecretQuestion1(String secretQuestion1) {
        this.secretQuestion1 = secretQuestion1;
    }
    public String getSecretQuestionAnswer1() {
        return this.secretQuestionAnswer1;
    }
    
    public void setSecretQuestionAnswer1(String secretQuestionAnswer1) {
        this.secretQuestionAnswer1 = secretQuestionAnswer1;
    }
    public String getSecretQuestion2() {
        return this.secretQuestion2;
    }
    
    public void setSecretQuestion2(String secretQuestion2) {
        this.secretQuestion2 = secretQuestion2;
    }
    public String getSecretQuestionAnswer2() {
        return this.secretQuestionAnswer2;
    }
    
    public void setSecretQuestionAnswer2(String secretQuestionAnswer2) {
        this.secretQuestionAnswer2 = secretQuestionAnswer2;
    }




}


