package com.onewifi.beans;
// Generated Nov 23, 2015 4:30:43 PM by Hibernate Tools 4.3.1.Final



/**
 * RetailerdeviceId generated by hbm2java
 */
public class RetailerdeviceId  implements java.io.Serializable {


     private String assignerId;
     private String deviceSerialNo;

    public RetailerdeviceId() {
    }

    public RetailerdeviceId(String assignerId, String deviceSerialNo) {
       this.assignerId = assignerId;
       this.deviceSerialNo = deviceSerialNo;
    }
   
    public String getAssignerId() {
        return this.assignerId;
    }
    
    public void setAssignerId(String assignerId) {
        this.assignerId = assignerId;
    }
    public String getDeviceSerialNo() {
        return this.deviceSerialNo;
    }
    
    public void setDeviceSerialNo(String deviceSerialNo) {
        this.deviceSerialNo = deviceSerialNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RetailerdeviceId) ) return false;
		 RetailerdeviceId castOther = ( RetailerdeviceId ) other; 
         
		 return ( (this.getAssignerId()==castOther.getAssignerId()) || ( this.getAssignerId()!=null && castOther.getAssignerId()!=null && this.getAssignerId().equals(castOther.getAssignerId()) ) )
 && ( (this.getDeviceSerialNo()==castOther.getDeviceSerialNo()) || ( this.getDeviceSerialNo()!=null && castOther.getDeviceSerialNo()!=null && this.getDeviceSerialNo().equals(castOther.getDeviceSerialNo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAssignerId() == null ? 0 : this.getAssignerId().hashCode() );
         result = 37 * result + ( getDeviceSerialNo() == null ? 0 : this.getDeviceSerialNo().hashCode() );
         return result;
   }   


}


