package com.onewifi.beans;
// Generated Oct 18, 2015 11:24:08 PM by Hibernate Tools 4.3.1.Final



/**
 * ThresholdId generated by hbm2java
 */
public class ThresholdId  implements java.io.Serializable {


     private Double thresHoldPercent;
     private Double thresHoldAmount;
     private Integer duration;

    public ThresholdId() {
    }

    public ThresholdId(Double thresHoldPercent, Double thresHoldAmount, Integer duration) {
       this.thresHoldPercent = thresHoldPercent;
       this.thresHoldAmount = thresHoldAmount;
       this.duration = duration;
    }
   
    public Double getThresHoldPercent() {
        return this.thresHoldPercent;
    }
    
    public void setThresHoldPercent(Double thresHoldPercent) {
        this.thresHoldPercent = thresHoldPercent;
    }
    public Double getThresHoldAmount() {
        return this.thresHoldAmount;
    }
    
    public void setThresHoldAmount(Double thresHoldAmount) {
        this.thresHoldAmount = thresHoldAmount;
    }
    public Integer getDuration() {
        return this.duration;
    }
    
    public void setDuration(Integer duration) {
        this.duration = duration;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ThresholdId) ) return false;
		 ThresholdId castOther = ( ThresholdId ) other; 
         
		 return ( (this.getThresHoldPercent()==castOther.getThresHoldPercent()) || ( this.getThresHoldPercent()!=null && castOther.getThresHoldPercent()!=null && this.getThresHoldPercent().equals(castOther.getThresHoldPercent()) ) )
 && ( (this.getThresHoldAmount()==castOther.getThresHoldAmount()) || ( this.getThresHoldAmount()!=null && castOther.getThresHoldAmount()!=null && this.getThresHoldAmount().equals(castOther.getThresHoldAmount()) ) )
 && ( (this.getDuration()==castOther.getDuration()) || ( this.getDuration()!=null && castOther.getDuration()!=null && this.getDuration().equals(castOther.getDuration()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getThresHoldPercent() == null ? 0 : this.getThresHoldPercent().hashCode() );
         result = 37 * result + ( getThresHoldAmount() == null ? 0 : this.getThresHoldAmount().hashCode() );
         result = 37 * result + ( getDuration() == null ? 0 : this.getDuration().hashCode() );
         return result;
   }   


}


