package com.onewifi.beans;
// Generated Nov 23, 2015 4:30:43 PM by Hibernate Tools 4.3.1.Final



/**
 * Threshold generated by hbm2java
 */
public class Threshold  implements java.io.Serializable {


     private double thresHoldPercent;
     private Double thresHoldAmount;
     private Integer duration;

    public Threshold() {
    }

	
    public Threshold(double thresHoldPercent) {
        this.thresHoldPercent = thresHoldPercent;
    }
    public Threshold(double thresHoldPercent, Double thresHoldAmount, Integer duration) {
       this.thresHoldPercent = thresHoldPercent;
       this.thresHoldAmount = thresHoldAmount;
       this.duration = duration;
    }
   
    public double getThresHoldPercent() {
        return this.thresHoldPercent;
    }
    
    public void setThresHoldPercent(double thresHoldPercent) {
        this.thresHoldPercent = thresHoldPercent;
    }
    public Double getThresHoldAmount() {
        return this.thresHoldAmount;
    }
    
    public void setThresHoldAmount(Double thresHoldAmount) {
        this.thresHoldAmount = thresHoldAmount;
    }
    public Integer getDuration() {
        return this.duration;
    }
    
    public void setDuration(Integer duration) {
        this.duration = duration;
    }




}


