package com.onewifi.beans;
// Generated Nov 23, 2015 4:30:43 PM by Hibernate Tools 4.3.1.Final



/**
 * Topuptypes generated by hbm2java
 */
public class Topuptypes  implements java.io.Serializable {


     private String topupType;
     private String topupTypeName;

    public Topuptypes() {
    }

	
    public Topuptypes(String topupType) {
        this.topupType = topupType;
    }
    public Topuptypes(String topupType, String topupTypeName) {
       this.topupType = topupType;
       this.topupTypeName = topupTypeName;
    }
   
    public String getTopupType() {
        return this.topupType;
    }
    
    public void setTopupType(String topupType) {
        this.topupType = topupType;
    }
    public String getTopupTypeName() {
        return this.topupTypeName;
    }
    
    public void setTopupTypeName(String topupTypeName) {
        this.topupTypeName = topupTypeName;
    }




}


