package com.onewifi.beans;
// Generated Nov 23, 2015 4:30:43 PM by Hibernate Tools 4.3.1.Final



/**
 * Userrole generated by hbm2java
 */
public class Userrole  implements java.io.Serializable {


     private String loginId;
     private String roleName;

    public Userrole() {
    }

    public Userrole(String loginId, String roleName) {
       this.loginId = loginId;
       this.roleName = roleName;
    }
   
    public String getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }




}


