package com.onewifi.beans;
// Generated Oct 18, 2015 11:24:08 PM by Hibernate Tools 4.3.1.Final



/**
 * UserroleId generated by hbm2java
 */
public class UserroleId  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
     private String loginId;
     private String roleName;

    public UserroleId() {
    }

    public UserroleId(String loginId, String roleName) {
       this.loginId = loginId;
       this.roleName = roleName;
    }
   
    public String getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserroleId) ) return false;
		 UserroleId castOther = ( UserroleId ) other; 
         
		 return ( (this.getLoginId()==castOther.getLoginId()) || ( this.getLoginId()!=null && castOther.getLoginId()!=null && this.getLoginId().equals(castOther.getLoginId()) ) )
 && ( (this.getRoleName()==castOther.getRoleName()) || ( this.getRoleName()!=null && castOther.getRoleName()!=null && this.getRoleName().equals(castOther.getRoleName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLoginId() == null ? 0 : this.getLoginId().hashCode() );
         result = 37 * result + ( getRoleName() == null ? 0 : this.getRoleName().hashCode() );
         return result;
   }   


}


